defaults:
  - username: example
    connection: ssh
    logLocation: "/home/vagrant/"
    downloadDirectory: "example-logs/"
    port: 22
    logName: example-log.txt
    deleteLog: false


nodes:
  - hostname: "192.168.33.10"
    username: vagrant
    password: vagrant
    port: 22
    logLocation: /home/vagrant/
    connection: ssh
  - hostname: "192.168.33.11"
    username: vagrant
    encryptedPassword: "U2FsdGVkX19A7vnbxoG6rh1sfGIqhNPbEofrr6NHRu8="
    port: 22
    logLocation: /home/vagrant/
    connection: ssh
  - hostname: "192.168.33.12"
    username: vagrant
    password: vagrant
    encryptedPassword: "U2FsdGVkX19A7vnbxoG6rh1sfGIqhNPbEofrr6NHRu8="
    port: 22
    logLocation: /home/vagrant/
    connection: ssh
  - hostname: "192.168.33.13"
    username: vagrant
    password: vagrant
    encryptedPassword: "U2FsdGVkX19A7vnbxoG6rh1sfGIqhNPbEofrr6NHRu8="
    port: 22
    logLocation: /home/vagrant/
    connection: ssh
  - hostname: "192.168.33.14"
    username: vagrant
    password: vagrant
    encryptedPassword: "U2FsdGVkX19A7vnbxoG6rh1sfGIqhNPbEofrr6NHRu8="
    port: 22
    logLocation: /home/vagrant/
    connection: ssh
