# This is an example yml file. Make sure to Vagrant up before using this config.

defaults:
  - username: example
    connection: ssh
    logLocation: "/home/vagrant/"
    downloadDirectory: "example-logs/"
    port: 22
    logName: chef-log.txt


nodes:
  - hostname: "192.168.33.10"
    username: vagrant
    password: vagrant
    port: 22
    logLocation: /home/vagrant/
    connection: ssh
  - hostname: "192.168.33.11"
    username: vagrant
    encryptedPassword: "U2FsdGVkX19A7vnbxoG6rh1sfGIqhNPbEofrr6NHRu8="
    port: 22
    logLocation: /home/vagrant/
    connection: ssh
  - hostname: "192.168.33.12"
    username: vagrant
    password: vagrant
    encryptedPassword: "U2FsdGVkX19A7vnbxoG6rh1sfGIqhNPbEofrr6NHRu8="
    port: 22
    logLocation: /home/vagrant/
    connection: ssh    
  - hostname: "192.168.33.13"
    username: vagrant
    password: vagrant
    encryptedPassword: "U2FsdGVkX19A7vnbxoG6rh1sfGIqhNPbEofrr6NHRu8="
    port: 22
    logLocation: /home/vagrant/
    connection: ssh    
  - hostname: "192.168.33.14"
    keyLocation: "/home/example/.ssh/id_rsa"
    encryptedPassword: "U2FsdGVkX19A7vnbxoG6rh1sfGIqhNPbEofrr6NHRu8="
    port: 22
    logLocation: /home/vagrant/
    connection: ssh    